### ISSUE TITLE
 TAQ2Chunks with chunk_type='symbols' yields empty numpy arrays

### ISSUE THREAD

**Issue by deniederhut** [dlab-projects/python-taq#23]
E.g.

```
generator = raw_taq.TAQ2Chunks(fp, chunk_type='symbols', chunksize=100000)
next(generator)
```

yields:

```
array([], 
      dtype=[('Time', '<f8'), ('hour', 'i1'), ('minute', 'i1'), ('msec', '<u2'), ('Exchange', 'S1'), ('Symbol_root', 'S6'), ('Symbol_suffix', 'S10'), ('Bid_Price', '<f8'), ('Bid_Size', '<i4'), ('Ask_Price', '<f8'), ('Ask_Size', '<i4'), ('Quote_Condition', 'S1'), ('Market_Maker', 'S4'), ('Bid_Exchange', 'S1'), ('Ask_Exchange', 'S1'), ('Sequence_Number', '<i8'), ('National_BBO_Ind', 'S1'), ('NASDAQ_BBO_Ind', 'S1'), ('Quote_Cancel_Correction', 'S1'), ('Source_of_Quote', 'S1'), ('Retail_Interest_Indicator_RPI', 'S1'), ('Short_Sale_Restriction_Indicator', 'S1'), ('LULD_BBO_Indicator_CQS', 'S1'), ('LULD_BBO_Indicator_UTP', 'S1'), ('FINRA_ADF_MPID_Indicator', 'S1'), ('SIP_generated_Message_Identifier', 'S1'), ('National_BBO_LULD_Indicator', 'S1')])
```

**Comment by deniederhut** [comment]
It looks like this only happens when `chunksize` is set to something smaller than the default, as TAQ2Chunks yields good symbol chunks when chunksize is set equal to the default value or larger.

@davclark any ideas?

**Comment by davclark** [comment]
That is super weird. I'll have a look. I'm messing with this code as we speak.

**Comment by davclark** [comment]
I think the problem was in [this line](https://github.com/dlab-projects/python-taq/blob/master/taq/raw_taq.py#L324), which I think also would prevent the system from finishing if you processed a whole file.

In an attempt to illustrate a different kind of architecture, I implemented [these generator functions]() which can be composed like so:

```
import taq
import taq.processing as tp

taq_in = taq.TAQ2Chunks('test-data/EQY_US_ALL_BBO_20140206.zip', do_process_chunk=False, chunksize=100000)
s = tp.split_chunks(taq_in, ['Symbol_root', 'Symbol_suffix'])
j = tp.joined_chunks(s, ['Symbol_root', 'Symbol_suffix'], 200000)

for chunk in j:
    do_some_math_or_whatever(chunk)
```

That logic guarantees you never pull any more than 300000 records into memory that are active (i.e., can't be garbage collected) at the same time. If you don't specify a row_limit for joined_chunks, you could use up all available memory.

Do you object to my replacing your logic with these utility functions?

Also - it would be cool to figure out a sensible way to specify a single memory budget and know how big the chunks coming off disk are. This would allow a bit more memory efficiency.

Lastly, I've started a different test_data script, as I realized as I started doing some testing that the structure of the file was too kerblooey. You can see it in the utility directory. It's not done, but should be obvious how to finish it. I'll plan to do it unless you're interested in doing so.

**Comment by deniederhut** [comment]
I'll have a look next week.

**Comment by davclark** [comment]
Please have a look! But no work needs doing anymore on this. It might be useful for you to look at the stuff in processing.py and see if it makes sense to do that kind of thing with some set of dask+blaze+etc.
